name: DockerGS Grasscutter Alpine (2.8 Early)
on:
  push:
    paths:
    - 'gs/os-alpine-gc'
    - 'gs/ver_gc-Patch-2.8-Early'
    - 'gs/entrypoint_gc.sh'
    - '.github/workflows/DockerGS_GC_Alpine_2.8_Early.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync DockerGS
      uses: actions/checkout@v3
    - name: Sync Grasscutter Yuuki
      uses: actions/checkout@v3
      with:
       repository: akbaryahya/Grasscutter-Yuuki
       ref: Patch-2.8-Early
       token: ${{ secrets.HUB_TOKEN }}
       path: gs/Grasscutter-Yuuki
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
       distribution: temurin
       java-version: '17'
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: cd gs && chmod +x run.sh && sh run.sh alpine build 5
    - name: Push Docker image
      run: cd gs && sh run.sh alpine push 5
    - name: Tar Folder Work Grasscutter
      run: cd gs && tar -cvf DockerGS_Grasscutter.tar work_gc
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
       name: DockerGS-Grasscutter
       path: gs/DockerGS_Grasscutter.tar