name: DockerGC Alpine (2.6 Early)
on:
  push:
    paths:
    - 'gc/os_alpine'
    - 'gc/VERSION_GC_Patch-2.6-Early'
    - 'gc/entrypoint.sh'
    - '.github/workflows/DockerGC_alpine_2.6_early.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync DockerGC
      uses: actions/checkout@v3
    - name: Sync Core
      uses: actions/checkout@v3
      with:
       repository: akbaryahya/GCPrivate
       ref: Patch-2.6-Early
       token: ${{ secrets.HUB_TOKEN }}
       path: gc/Grasscutter
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
       distribution: temurin
       java-version: '17'
    - name: Cache gradle files
      uses: actions/cache@v2
      with:
       path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
        ./.gradle/loom-cache
       key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
       restore-keys: |
        ${{ runner.os }}-gradle-
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: cd gc && chmod +x run.sh && sh run.sh alpine build 1
    - name: Push Docker image
      run: cd gc && sh run.sh alpine push 1
    - name: Tar Folder Work
      run: cd gc && tar -cvf dockergc.tar work
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
       name: DockerGC
       path: gc/dockergc.tar